export const ImageHub = {
    CHARACTER: {
        STANDING: ["./assets/img/character/dodge/stehen.png"],
        IDLE_0: "./assets/img/character/idle/idle0.png",
        LONG_IDLE: [
            "./assets/img/character/long_idle/long_idle0.webp",
            "./assets/img/character/long_idle/long_idle1.webp",
            "./assets/img/character/long_idle/long_idle2.png",
            "./assets/img/character/long_idle/long_idle3.png",
            "./assets/img/character/long_idle/long_idle4.png",
            "./assets/img/character/long_idle/long_idle5.png",
            "./assets/img/character/long_idle/long_idle6.png",
            "./assets/img/character/long_idle/long_idle7.png",
        ],
        WALKING: [
            "./assets/img/character/walk/walk1.png",
            "./assets/img/character/walk/walk2.png",
            "./assets/img/character/walk/walk3.png",
            "./assets/img/character/walk/walk4.png",
            "./assets/img/character/walk/walk5.png",
            "./assets/img/character/walk/walk6.png",
            "./assets/img/character/walk/walk7.png",
            "./assets/img/character/walk/walk8.png",
            "./assets/img/character/walk/walk9.png",
        ],
        JUMPING: [
            "./assets/img/character/springen/sprung1.png",
            "./assets/img/character/springen/sprung2.png",
            "./assets/img/character/springen/sprung3.png",
            "./assets/img/character/springen/sprung4.png",
            "./assets/img/character/springen/sprung5.png",
            "./assets/img/character/springen/sprung6.png",
            "./assets/img/character/springen/sprung7.png",
            "./assets/img/character/springen/sprung8.png",
        ],
        DODGING: [
            "./assets/img/character/dodge/dodge1.png",
            "./assets/img/character/dodge/dodge2.png",
            "./assets/img/character/dodge/dodge3.png",
            "./assets/img/character/dodge/dodge4.png",
            "./assets/img/character/dodge/dodge5.png",
            "./assets/img/character/dodge/dodge6.png",
        ],
        CROUCHING: [
            "./assets/img/character/crawling/crawl0.png",
            "./assets/img/character/crawling/crawl1.png",
            "./assets/img/character/crawling/crawl2.png",
            "./assets/img/character/crawling/crawl3.png",
            "./assets/img/character/crawling/crawl4.png",
            "./assets/img/character/crawling/crawl5.png",
            "./assets/img/character/crawling/crawl6.png",
            "./assets/img/character/crawling/crawl7.png",
        ],

        HURT: [
            "./assets/img/character/hurt/hurt1.png",
            "./assets/img/character/hurt/hurt2.png",
            "./assets/img/character/hurt/hurt3.png",
            "./assets/img/character/hurt/hurt4.png",
            "./assets/img/character/hurt/hurt5.png",
        ],
        HUD: {
            HP_BARS: [
                "./assets/img/hud/hp_bar0.png",
                "./assets/img/hud/hp_bar1.png",
                "./assets/img/hud/hp_bar2.png",
                "./assets/img/hud/hp_bar3.png",
                "./assets/img/hud/hp_bar4.png",
                "./assets/img/hud/hp_bar5.png",
            ],
        },
        DEAD: [
            "./assets/img/character/dead/dead1.png",
            "./assets/img/character/dead/dead2.png",
            "./assets/img/character/dead/dead3.png",
            "./assets/img/character/dead/dead4.png",
            "./assets/img/character/dead/dead5.png",
            "./assets/img/character/dead/dead6.png",
            "./assets/img/character/dead/dead7.png",
        ],
        ATTACK: [
            "./assets/img/character/angreifen/ausholen2.webp",
            "./assets/img/character/angreifen/angriff.webp",
        ],
    },

    SPIDER: {
        WALKING: [
            "./assets/img/monster/spider/spider_walk0.png",
            "./assets/img/monster/spider/spider_walk1.png",
            "./assets/img/monster/spider/spider_walk2.png",
            "./assets/img/monster/spider/spider_walk3.png",
            "./assets/img/monster/spider/spider_walk4.png",
            "./assets/img/monster/spider/spider_walk5.png",
            "./assets/img/monster/spider/spider_walk6.png",
        ],
    },

    GOLEM: {
        WALKING: [
            "./assets/img/monster/golem1.png",
            "./assets/img/monster/golem2.png",
            "./assets/img/monster/golem3.png",
            "./assets/img/monster/golem4.png",
            "./assets/img/monster/golem5.png",
            "./assets/img/monster/golem6.png",
            "./assets/img/monster/golem7.png",
            "./assets/img/monster/golem8.png",
        ],
    },

    BOSS: {
        BOSS_HP_BARS: [
            "./assets/img/hud/hp_bar_boss0.png",
            "./assets/img/hud/hp_bar_boss1.png",
            "./assets/img/hud/hp_bar_boss2.png",
            "./assets/img/hud/hp_bar_boss3.png",
            "./assets/img/hud/hp_bar_boss4.png",
            "./assets/img/hud/hp_bar_boss5.png",
        ],
        HURT: "./assets/img/monster/dmg_reaction_boss.png",
        DEAD: [
            "./assets/img/monster/final_death0.webp",
            "./assets/img/monster/final_death1.png",
            "./assets/img/monster/final_death2.png",
            "./assets/img/monster/final_death3.png",
            "./assets/img/monster/final_death4.png",
            "./assets/img/monster/final_death5.png",
            "./assets/img/monster/final_death6.png",
        ],
    },

    HUD: {
        CORE_BARS: [
            "./assets/img/hud/core_bar0.png",
            "./assets/img/hud/core_bar1.png",
            "./assets/img/hud/core_bar2.png",
            "./assets/img/hud/core_bar3.png",
            "./assets/img/hud/core_bar4.png",
            "./assets/img/hud/core_bar5.png",
        ],
        COIN_BARS: [
            "./assets/img/hud/coin_bar0.png",
            "./assets/img/hud/coin_bar1.png",
            "./assets/img/hud/coin_bar2.png",
            "./assets/img/hud/coin_bar3.png",
            "./assets/img/hud/coin_bar4.png",
            "./assets/img/hud/coin_bar5.png",
        ],
    },

    COINS: [
        "./assets/img/drops/coin0.png",
        "./assets/img/drops/coin1.png",
        "./assets/img/drops/coin2.png",
        "./assets/img/drops/coin3.png",
        "./assets/img/drops/coin4.png",
    ],
};
